version: "3.8"

services:
  assistant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:22"  # Porta SSH do container
    volumes:
      - .:/app                # Código-fonte para desenvolvimento ágil
      - ./models:/app/models  # Modelos persistentes
      - ./logs:/app/logs      # Logs persistentes
    restart: always
